/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-12-30 15:50:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class alumniLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/alumni_Login.css\">\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css\" integrity=\"sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("   <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	\r\n");
      out.write("function validPass(str) {\r\n");
      out.write("    var sp = document.getElementById(\"spPass\");\r\n");
      out.write("    if (str.length < 8) {\r\n");
      out.write("        sp.innerHTML = \"Password must be at least 8 characters long\";\r\n");
      out.write("        sp.style.color = \"red\";\r\n");
      out.write("        sp.style.backgroundColor = \"white\";\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("    if (!/[A-Z]/.test(str)) {\r\n");
      out.write("        sp.innerHTML = \"Password must contain at least one uppercase letter\";\r\n");
      out.write("        sp.style.color = \"red\";\r\n");
      out.write("        sp.style.backgroundColor = \"white\";\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("    if (!/[a-z]/.test(str)) {\r\n");
      out.write("        sp.innerHTML = \"Password must contain at least one lowercase letter\";\r\n");
      out.write("        sp.style.color = \"red\";\r\n");
      out.write("        sp.style.backgroundColor = \"white\";\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("    if (!/[0-9]/.test(str)) {\r\n");
      out.write("        sp.innerHTML = \"Password must contain at least one number\";\r\n");
      out.write("        sp.style.color = \"red\";\r\n");
      out.write("        sp.style.backgroundColor = \"white\";\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("    if (!/[!@#$%^&*(),.?\":{}|<>]/.test(str)) {\r\n");
      out.write("        sp.innerHTML = \"Password must contain at least one special character\";\r\n");
      out.write("        sp.style.color = \"red\";\r\n");
      out.write("        sp.style.backgroundColor = \"white\";\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("    sp.innerHTML = \"\";\r\n");
      out.write("    sp.style.color = \"white\";\r\n");
      out.write("    sp.style.backgroundColor = \"white\";\r\n");
      out.write("}\r\n");
      out.write("function nameVal(str)\r\n");
      out.write("{     let flag=false;\r\n");
      out.write("    var spnElement;\r\n");
      out.write("    for(var i=0;i<str.length;i++)\r\n");
      out.write("    {\r\n");
      out.write("        let ascii=str.charCodeAt(i);\r\n");
      out.write("        if(!( (ascii>=65&& ascii<=97)||(ascii>=97 && ascii<=122) ||ascii==32))\r\n");
      out.write("        {\r\n");
      out.write("           flag=true;\r\n");
      out.write("           break;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    if(flag)\r\n");
      out.write("    {\r\n");
      out.write("    spnElement=document.getElementById(\"na\");\r\n");
      out.write("    spnElement.innerHTML=\"invalid name\";\r\n");
      out.write("    spnElement.style.color=\"red\";\r\n");
      out.write("  \r\n");
      out.write("    }\r\n");
      out.write("    else{\r\n");
      out.write("     spnElement=document.getElementById(\"na\");\r\n");
      out.write("     spnElement.innerHTML=\"\";\r\n");
      out.write("     spnElement.style.color=\"black\";\r\n");
      out.write("    \r\n");
      out.write("    }\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <body>\r\n");
      out.write("    <div class=\"fi\" >\r\n");
      out.write("        <img  src=\"css/rmoveBagroundCap.png\" id=\"ima\">\r\n");
      out.write("        </div>\r\n");
      out.write("       <div class=\"Container \">\r\n");
      out.write("       \r\n");
      out.write("         \r\n");
      out.write("          <form name=\"frm\" action=\"ValidAlumni\" method=\"post\">\r\n");
      out.write("          \r\n");
      out.write("         <div class=\"login\" id=\"loginmid\">\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("               <h1>Login</h1>\r\n");
      out.write("               <div class=\"input-box\">\r\n");
      out.write("                   <input type=\"text\" id=\"na\" name=\"name\" value=\"\" placeholder=\"Enter Username\" onkeyup=\"nameVal(this.value)\"><br><span id=\"na\"></span> \r\n");
      out.write("               </div>	\r\n");
      out.write("       \r\n");
      out.write("               <div class=\"input-box\">\r\n");
      out.write("                  <input type=\"password\" name=\"pass\" value=\"\" placeholder=\"Enter password\"  onkeyup=\"validPass(this.value)\" required><br><span id=\"spPass\"></span>\r\n");
      out.write("               </div>\r\n");
      out.write("       \r\n");
      out.write("               <div class=\"remember-forgot\">\r\n");
      out.write("                   <label><input type=\"checkbox\">Remember me\r\n");
      out.write("                   </label>\r\n");
      out.write("                   <a href=\"#\">Forgot password</a>\r\n");
      out.write("       \r\n");
      out.write("               </div>\r\n");
      out.write("               \r\n");
      out.write("                \r\n");
      out.write("                <button type=\"submit\" name=\"s\" value=\"Login\"  class=\"btn\" class=\"btn btn-outline-danger\" id=\"btn\" style=\"margin-top:2%\" onclick=\"validateForm()\">Login</button>\r\n");
      out.write("              <div class=\"register-link\">\r\n");
      out.write("                       <p style=\"margin-left: 11%;color: black\">Don't have an account? <a href=\"alumniRegister.jsp\" style=\"color: black\">Registration</a></p>\r\n");
      out.write("              </div>\r\n");
      out.write("               <div class=\"register-link\">\r\n");
      out.write("                       <p style=\"margin-left: 10% ;color: black; \">Admin Login Here <a href=\"adminLogin.jsp\" style=\"color: black\" >Admin Login</a></p>\r\n");
      out.write("              </div>\r\n");
      out.write("               \r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          </form>\r\n");
      out.write("          \r\n");
      out.write("          </div>\r\n");
      out.write("          <script >\r\n");
      out.write("               function validateForm()\r\n");
      out.write("               {\r\n");
      out.write("            	  \r\n");
      out.write("            	   var name=document.getElementById(\"na\").value;\r\n");
      out.write("            	   var pass=document.getElementById(\"pa\").value;\r\n");
      out.write("					\r\n");
      out.write("            	   if(name==\"\"||pass==\"\")\r\n");
      out.write("            		   {\r\n");
      out.write("            		     alert(\"All Field must be filled \");\r\n");
      out.write("            		    \r\n");
      out.write("            		   }\r\n");
      out.write("               }\r\n");
      out.write("          \r\n");
      out.write("          </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
