/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-12-30 15:51:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class alumniRegister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Admin Dashboard</title>\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("<!-- Font Awesome for icons -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\">\r\n");
      out.write("<!-- Custom CSS  -->\r\n");
      out.write("<style>\r\n");
      out.write("  \r\n");
      out.write(".container {\r\n");
      out.write("	max-width: 900px;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("	margin-top: 50px;\r\n");
      out.write("	margin-right: 5%;\r\n");
      out.write("	padding: 30px;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	\r\n");
      out.write("	box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	animation: fadeIn 2s ease; \r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("@keyframes fadeIn {\r\n");
      out.write("  from {\r\n");
      out.write("    opacity: 0;\r\n");
      out.write("    transform: translateY(-20px);\r\n");
      out.write("  }\r\n");
      out.write("  to {\r\n");
      out.write("    opacity: 1;\r\n");
      out.write("    transform: translateY(0);\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2 {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin-bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label {\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"text\"], select {\r\n");
      out.write("	width: 90%;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("	border: 1px solid #ced4da;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button[type=\"submit\"] {\r\n");
      out.write("	width: 90%;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	background-color: #007bff;\r\n");
      out.write("	border: none;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	color: white;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button[type=\"submit\"]:hover {\r\n");
      out.write("	background-color: #0056b3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script type='text/javascript'>\r\n");
      out.write("    function nameVal(str)\r\n");
      out.write("         {     let flag=false;\r\n");
      out.write("             var spnElement;\r\n");
      out.write("             for(var i=0;i<str.length;i++)\r\n");
      out.write("             {\r\n");
      out.write("                 let ascii=str.charCodeAt(i);\r\n");
      out.write("                 if(!( (ascii>=65&& ascii<=97)||(ascii>=97 && ascii<=122) ||ascii==32))\r\n");
      out.write("                 {\r\n");
      out.write("                    flag=true;\r\n");
      out.write("                    break;\r\n");
      out.write("                 }\r\n");
      out.write("             }\r\n");
      out.write("             if(flag)\r\n");
      out.write("             {\r\n");
      out.write("             spnElement=document.getElementById(\"na\");\r\n");
      out.write("             spnElement.innerHTML=\"invalid name\";\r\n");
      out.write("             spnElement.style.color=\"red\";\r\n");
      out.write("           \r\n");
      out.write("             }\r\n");
      out.write("             else{\r\n");
      out.write("              spnElement=document.getElementById(\"na\");\r\n");
      out.write("              spnElement.innerHTML=\"\";\r\n");
      out.write("              spnElement.style.color=\"white\";\r\n");
      out.write("             \r\n");
      out.write("             }\r\n");
      out.write("            \r\n");
      out.write("         }\r\n");
      out.write("     var spanElement;\r\n");
      out.write("     function Emailvaild(str)\r\n");
      out.write("     {   var flag=false;\r\n");
      out.write("         var index=str.indexOf(\"@\");\r\n");
      out.write("         var count=0;\r\n");
      out.write("         for(var i=0;i<str.length;i++)\r\n");
      out.write("         {\r\n");
      out.write("              if(str.charAt(i)=='@')\r\n");
      out.write("             { \r\n");
      out.write("                 ++count;\r\n");
      out.write("             }\r\n");
      out.write("         }\r\n");
      out.write("         if(index!=-1 && index>0 && count==1)\r\n");
      out.write("         {  \r\n");
      out.write("              var epart=str.substring((index+1),str.length);\r\n");
      out.write("             index=epart.indexOf(\".\");\r\n");
      out.write("             if(index!=-1 && (index==epart.length-4 || index==epart.length-3))\r\n");
      out.write("             {\r\n");
      out.write("                 spanElement=document.getElementById(\"email\");\r\n");
      out.write("                 spanElement.innerHTML=\"valid email address dot present\";\r\n");
      out.write("                 spanElement.style.color=\"red\";\r\n");
      out.write("            }\r\n");
      out.write("           else\r\n");
      out.write("             {\r\n");
      out.write("                 spanElement=document.getElementById(\"email\");\r\n");
      out.write("                 spanElement.innerHTML=\"Invalid Email Address \";\r\n");
      out.write("                 spanElement.style.color=\"red\";\r\n");
      out.write("             }\r\n");
      out.write(" \r\n");
      out.write("         }\r\n");
      out.write("         else\r\n");
      out.write("         {\r\n");
      out.write("             spanElement=document.getElementById(\"email\");\r\n");
      out.write("             spanElement.innerHTML=\"Invalid Email Address \"+count;\r\n");
      out.write("             spanElement.style.color=\"red\";\r\n");
      out.write("         }\r\n");
      out.write("     }\r\n");
      out.write(" \r\n");
      out.write("     function MobileValidate(str)\r\n");
      out.write("     {   \r\n");
      out.write("         var flag=false;\r\n");
      out.write("         var spanElement;\r\n");
      out.write("         for(var i=0;i<str.length;i++)\r\n");
      out.write("         {\r\n");
      out.write("             var ascii=str.charCodeAt(i);\r\n");
      out.write("             if(!((ascii>=48 && ascii<=57) && (str.length==10) && (!(str.charCodeAt(0)>=49 && str.charCodeAt(0)<=53))))\r\n");
      out.write("            { \r\n");
      out.write("                 flag=true;\r\n");
      out.write("                 break;\r\n");
      out.write("           }\r\n");
      out.write("        }  \r\n");
      out.write("        if(flag)\r\n");
      out.write("        { \r\n");
      out.write("                 spanElement=document.getElementById(\"co\");\r\n");
      out.write("                 spanElement.innerHTML=\"invalid Contact\";\r\n");
      out.write("                 spanElement.style.color=\"red\";\r\n");
      out.write("                 spanElement.styel.backgroundColor=\"white\";\r\n");
      out.write("        }\r\n");
      out.write("        else\r\n");
      out.write("        {\r\n");
      out.write("             spanElement=document.getElementById(\"co\");\r\n");
      out.write("             spanElement.innerHTML=\"\";\r\n");
      out.write("             spanElement.style.color=\"white\";\r\n");
      out.write("             spanElement.styel.backgroundColor=\"white\";\r\n");
      out.write(" \r\n");
      out.write("        }   \r\n");
      out.write("     }\r\n");
      out.write("    \r\n");
      out.write("     function validPass(str) {\r\n");
      out.write("     var sp = document.getElementById(\"spPass\");\r\n");
      out.write("     if (str.length < 8) {\r\n");
      out.write("         sp.innerHTML = \"Password must be at least 8 characters long\";\r\n");
      out.write("         sp.style.color = \"red\";\r\n");
      out.write("         sp.style.backgroundColor = \"white\";\r\n");
      out.write("         return;\r\n");
      out.write("     }\r\n");
      out.write("     if (!/[A-Z]/.test(str)) {\r\n");
      out.write("         sp.innerHTML = \"Password must contain at least one uppercase letter\";\r\n");
      out.write("         sp.style.color = \"red\";\r\n");
      out.write("         sp.style.backgroundColor = \"white\";\r\n");
      out.write("         return;\r\n");
      out.write("     }\r\n");
      out.write("     if (!/[a-z]/.test(str)) {\r\n");
      out.write("         sp.innerHTML = \"Password must contain at least one lowercase letter\";\r\n");
      out.write("         sp.style.color = \"red\";\r\n");
      out.write("         sp.style.backgroundColor = \"white\";\r\n");
      out.write("         return;\r\n");
      out.write("     }\r\n");
      out.write("     if (!/[0-9]/.test(str)) {\r\n");
      out.write("         sp.innerHTML = \"Password must contain at least one number\";\r\n");
      out.write("         sp.style.color = \"red\";\r\n");
      out.write("         sp.style.backgroundColor = \"white\";\r\n");
      out.write("         return;\r\n");
      out.write("     }\r\n");
      out.write("     if (!/[!@#$%^&*(),.?\":{}|<>]/.test(str)) {\r\n");
      out.write("         sp.innerHTML = \"Password must contain at least one special character\";\r\n");
      out.write("         sp.style.color = \"red\";\r\n");
      out.write("         sp.style.backgroundColor = \"white\";\r\n");
      out.write("         return;\r\n");
      out.write("     }\r\n");
      out.write("     sp.innerHTML = \"\";\r\n");
      out.write("     sp.style.color = \"white\";\r\n");
      out.write("     sp.style.backgroundColor = \"white\";\r\n");
      out.write(" }\r\n");
      out.write("  </script>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("   <div class=\"container-fluid  \">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          \r\n");
      out.write("			\r\n");
      out.write("			<div class=\"col-md-10 col-sm-12-mt-5 main-contents\">\r\n");
      out.write("			\r\n");
      out.write("			     <div class=\"container bg-light\">\r\n");
      out.write("			        <div class=\"row\">\r\n");
      out.write("			        \r\n");
      out.write("			         <div class=\"col-md-6 col-sm-12\">\r\n");
      out.write("			             \r\n");
      out.write("			             <img src=\"imag/alumni7.jpg\" alt=\"Patient Registration\"\r\n");
      out.write("						class=\"img-fluid mt-5\">\r\n");
      out.write("						\r\n");
      out.write("						<h5 id=\"response\" class=\"mt-5\"></h5>\r\n");
      out.write("			         \r\n");
      out.write("			         \r\n");
      out.write("			         </div>\r\n");
      out.write("			         \r\n");
      out.write("			         <div class=\"col-md-6 col-sm-12 sub \">\r\n");
      out.write("\r\n");
      out.write("							<h2\r\n");
      out.write("								style=\"color: #093b6a; font-family: 'Times New Roman', Times, serif;\">Registration Page</h2>\r\n");
      out.write("							<form name='frm' method='POST' action='register'>\r\n");
      out.write("								<div class=\"form-group\">\r\n");
      out.write("                <label for=\"Name\">Enter Name:</label> <input\r\n");
      out.write("                    type=\"text\" class=\"form-control\" id=\"patientName\"  value=\"\"\r\n");
      out.write("                    name=\"name\" placeholder=\"Enter Alumni name\" onkeyup='nameVal(this.value) 'required>\r\n");
      out.write("                   <span id=\"na\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"email\">Enter Email</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"email\" name=\"email\" placeholder=\"Enter Alumni Email Id\" onkeyup=\"Emailvaild(this.value)\" required>\r\n");
      out.write("                <span id=\"email\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("							\r\n");
      out.write("                <label for=\"contact\">Contact No</label>\r\n");
      out.write("                 <input type=\"text\"   class=\"form-control\" id=\"contact\" name=\"contct\"  value=\"\"\r\n");
      out.write("                    placeholder=\"Enter contact number\" onkeyup='MobileValidate(this.value)' required>\r\n");
      out.write("                    <span id=\"co\"></span>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"username\">Username</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"username\" name=\"username\" placeholder=\"Enter Username\" onkeyup=\"nameVal(this.value)\" required>\r\n");
      out.write("                        <span id=\"d\"></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"Password\">Password</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"Password\" name=\"pass\" placeholder=\"Enter Password\" onkeyup=\"validPass(this.value)\" required>\r\n");
      out.write("                        <span id=\"spPass\"></span>\r\n");
      out.write("                    </div><br><br>\r\n");
      out.write("                    </div>\r\n");
      out.write("								<button style=\"width: 30%; text-align: center;  margin-left: 56%\" type=\"submit\" name=\"s\" class=\"btn btn-primary\">Submit</button>\r\n");
      out.write("							</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("			        \r\n");
      out.write("			        </div>\r\n");
      out.write("			     \r\n");
      out.write("			     \r\n");
      out.write("			     </div>\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			</div>\r\n");
      out.write("          \r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("   </div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
