/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-04-26 17:26:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class homepage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Carsercice Project</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"Homepag.css\">\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write(" </head>\r\n");
      out.write(" <body>\r\n");
      out.write("\r\n");
      out.write(" <div class=\"container\">\r\n");
      out.write("    <div class=\"row mt-2\">\r\n");
      out.write("      <div class=\"col-sm-4 logo bg-light\">\r\n");
      out.write("         <h2>JANTA<span>Garage</span></h2>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-sm-8 Navbar\">\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg bg-body-secondary\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("              <a class=\"navbar-brand\" href=\"#\"><span>Royal</span>Car</a>\r\n");
      out.write("              <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("              </button>\r\n");
      out.write("              <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("                <ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                     <a class=\"nav-link\" href=\"Adminlogin.html\">Admin</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                     <a class=\"nav-link\" href=\"Employelogin.jsp\">Employee</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                 <li class=\"nav-item\">\r\n");
      out.write("                      <a class=\"nav-link\" href=\"CustomerLogin.jsp\">Appointment</a>\r\n");
      out.write("                   </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#about\">About</a>\r\n");
      out.write("                 </li>\r\n");
      out.write("                 <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#Sercices\">Services</a>\r\n");
      out.write("                 </li>\r\n");
      out.write("                 <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#Team\">Team</a>\r\n");
      out.write("                 </li>\r\n");
      out.write("                 <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#Review\">Reviews</a>\r\n");
      out.write("                 </li>\r\n");
      out.write("                 <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#contact\">Contact</a>\r\n");
      out.write("                 </li>\r\n");
      out.write("                  \r\n");
      out.write("                </ul>\r\n");
      out.write("               \r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </nav>\r\n");
      out.write("      </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"row carsoul\">\r\n");
      out.write("    <div class=\"col-sm-12\">\r\n");
      out.write("        <div id=\"carouselExampleCaptions\" class=\"carousel slide\">\r\n");
      out.write("            <div class=\"carousel-indicators\">\r\n");
      out.write("              <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"0\" class=\"active\" aria-current=\"true\" aria-label=\"Slide 1\"></button>\r\n");
      out.write("              <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"1\" aria-label=\"Slide 2\"></button>\r\n");
      out.write("              <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"2\" aria-label=\"Slide 3\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"carousel-inner\">\r\n");
      out.write("              <div class=\"carousel-item active\">\r\n");
      out.write("                <img src=\"imges/img2\" class=\"d-block w-100 \" alt=\"...\">\r\n");
      out.write("                <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                  <h3 class=\"animated fadeInDown\" style=\"animation-delay:1s;\">AUTO REPAIR</h3>\r\n");
      out.write("                  <h1 class=\"servic\">SERVICES</h1>\r\n");
      out.write("\r\n");
      out.write("                  <p>We all take care of all your auto repair needs: breaks, tires, oil, and everything in between..........</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"carousel-item\">\r\n");
      out.write("                <img src=\"imges/redcaar\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("                <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                    <h3 class=\"animated fadeInDown\" style=\"animation-delay:1s;\">AUTO REPAIR</h3>\r\n");
      out.write("                    <h1 class=\"servic\">SERVICES</h1>\r\n");
      out.write("  \r\n");
      out.write("                  <p>We all take care of all your auto repair needs: breaks, tires, oil, and everything in between..........</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"carousel-item\">\r\n");
      out.write("                <img src=\"imges/crosouls\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("                <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                    <h3 class=\"animated fadeInDown\" style=\"animation-delay:1s;\">AUTO REPAIR</h3>\r\n");
      out.write("                    <h1 class=\"servic\">SERVICES</h1>\r\n");
      out.write("  \r\n");
      out.write("                  <p>We all take care of all your auto repair needs: breaks, tires, oil, and everything in between..........</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide=\"prev\">\r\n");
      out.write("              <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("              <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide=\"next\">\r\n");
      out.write("              <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("              <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("            </button>\r\n");
      out.write("          </div>\r\n");
      out.write("     </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"row about\" id=\"about\">\r\n");
      out.write("    <h1>About<span>US</span></h1>\r\n");
      out.write("    <div class=\"col-sm-6\">\r\n");
      out.write("      <img src=\"imges/about@.jpg\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-6\">\r\n");
      out.write("      <h2>Royal<span>Car</span> Service</h2>\r\n");
      out.write("      <p>When it comes to repairing or doing checkups on your car's, all our team combined has almost a \r\n");
      out.write("        century of practical experience. We aim to make our service as reasonably priced as possible. \r\n");
      out.write("        That's why we cut on all unessential business expenses.</p>\r\n");
      out.write("        <h2>Why Choose Us</h2>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li>FREE Loaner Cars;</li>\r\n");
      out.write("          <li>FREE Shuttle Service;</li>\r\n");
      out.write("          <li>Te Dent repair</li>\r\n");
      out.write("          <li>Paint scratch repair</li>\r\n");
      out.write("          <li>Tire installation</li>\r\n");
      out.write("          <li>Wheel alinment</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write(" <div class=\"row Services\" id=\"Sercices\">\r\n");
      out.write("  <h2>OUR<span>SERVICE</span></h2>\r\n");
      out.write("    <div class=\"col-12 Card\">\r\n");
      out.write("        <div class=\"row row-cols-1 row-cols-md-3 g-4\">\r\n");
      out.write("            <div class=\"col\">\r\n");
      out.write("              <div class=\"card h-100\">\r\n");
      out.write("                <img src=\"imges/oil3.jpeg\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <h5 class=\"card-title\">Oil change</h5>\r\n");
      out.write("                  <p class=\"card-text\">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-footer\">\r\n");
      out.write("                  <small class=\"text-body-secondary\">Last updated 3 mins ago</small>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col\">\r\n");
      out.write("              <div class=\"card h-100\">\r\n");
      out.write("                <img src=\"imges/img6.png\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <h5 class=\"card-title\">Tir installation</h5>\r\n");
      out.write("                  <p class=\"card-text\">This card has supporting text below as a natural lead-in to additional content.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-footer\">\r\n");
      out.write("                  <small class=\"text-body-secondary\">Last updated 3 mins ago</small>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col\">\r\n");
      out.write("              <div class=\"card h-100\">\r\n");
      out.write("                <img src=\"imges/air.jpg\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <h5 class=\"card-title\">Air Conditioning</h5>\r\n");
      out.write("                  <p class=\"card-text\">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-footer\">\r\n");
      out.write("                  <small class=\"text-body-secondary\">Last updated 3 mins ago</small>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row Team\" id=\"Team\">\r\n");
      out.write("      <h2>OUR<span>TEAM</span></h2>\r\n");
      out.write("      <div class=\"col-12\">\r\n");
      out.write("        <div class=\"card-group\">\r\n");
      out.write("          <div class=\"card\">\r\n");
      out.write("            <img src=\"imges/sam\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <h5 class=\"card-title\">Sam</h5>\r\n");
      out.write("              <p class=\"card-text\">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>\r\n");
      out.write("              <p class=\"card-text\"><small class=\"text-muted\">Last updated 3 mins ago</small></p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"card\">\r\n");
      out.write("            <img src=\"imges/Alisa\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <h5 class=\"card-title\">Alisa</h5>\r\n");
      out.write("              <p class=\"card-text\">This card has supporting text below as a natural lead-in to additional content.</p>\r\n");
      out.write("              <p class=\"card-text\"><small class=\"text-muted\">Last updated 3 mins ago</small></p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"card\">\r\n");
      out.write("            <img src=\"imges/Parker\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <h5 class=\"card-title\">Parker</h5>\r\n");
      out.write("              <p class=\"card-text\">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>\r\n");
      out.write("              <p class=\"card-text\"><small class=\"text-muted\">Last updated 3 mins ago</small></p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("                                               <!----------------------------- OUR REVIEW -------------------------------->\r\n");
      out.write("    <div class=\"row Review\" id=\"Review\">\r\n");
      out.write("      <div class=\"textR\">\r\n");
      out.write("        <h2>OUR <SPan>REVIEW</SPan></h2>\r\n");
      out.write("        <section>\r\n");
      out.write("          <div class=\"row d-flex justify-content-center\">\r\n");
      out.write("           \r\n");
      out.write("        \r\n");
      out.write("          <div class=\"row text-center d-flex align-items-stretch\">\r\n");
      out.write("            <div class=\"col-md-4 mb-5 mb-md-0 d-flex align-items-stretch\">\r\n");
      out.write("              <div class=\"card testimonial-card\">\r\n");
      out.write("                <div class=\"card-up\" style=\"background-color: #9d789b;\"></div>\r\n");
      out.write("                <div class=\"avatar mx-auto bg-white\">\r\n");
      out.write("                  <img src=\"https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(1).webp\"\r\n");
      out.write("                    class=\"rounded-circle img-fluid\" />\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <h4 class=\"mb-4\">Maria Smantha</h4>\r\n");
      out.write("                  <hr />\r\n");
      out.write("                  <p class=\"dark-grey-text mt-4\">\r\n");
      out.write("                    <i class=\"fas fa-quote-left pe-2\"></i>Lorem ipsum dolor sit amet eos adipisci,\r\n");
      out.write("                    consectetur adipisicing elit.\r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4 mb-5 mb-md-0 d-flex align-items-stretch\">\r\n");
      out.write("              <div class=\"card testimonial-card\">\r\n");
      out.write("                <div class=\"card-up\" style=\"background-color: #7a81a8;\"></div>\r\n");
      out.write("                <div class=\"avatar mx-auto bg-white\">\r\n");
      out.write("                  <img src=\"https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(2).webp\"\r\n");
      out.write("                    class=\"rounded-circle img-fluid\" />\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <h4 class=\"mb-4\">Lisa Cudrow</h4>\r\n");
      out.write("                  <hr />\r\n");
      out.write("                  <p class=\"dark-grey-text mt-4\">\r\n");
      out.write("                    <i class=\"fas fa-quote-left pe-2\"></i>Neque cupiditate assumenda in maiores\r\n");
      out.write("                    repudi mollitia architecto.\r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4 mb-0 d-flex align-items-stretch\">\r\n");
      out.write("              <div class=\"card testimonial-card\">\r\n");
      out.write("                <div class=\"card-up\" style=\"background-color: #6d5b98;\"></div>\r\n");
      out.write("                <div class=\"avatar mx-auto bg-white\">\r\n");
      out.write("                  <img src=\"https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(9).webp\"\r\n");
      out.write("                    class=\"rounded-circle img-fluid\" />\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <h4 class=\"mb-4\">John Smith</h4>\r\n");
      out.write("                  <hr />\r\n");
      out.write("                  <p class=\"dark-grey-text mt-4\">\r\n");
      out.write("                    <i class=\"fas fa-quote-left pe-2\"></i>Delectus impedit saepe officiis ab\r\n");
      out.write("                    aliquam repellat rem unde ducimus.\r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </section>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write(" \r\n");
      out.write(" <!-- Contact form -->\r\n");
      out.write("  <dic class=\"row Contact\" >\r\n");
      out.write("    <div class=\"col-12\">\r\n");
      out.write("      <!-- Contact 1 - Bootstrap Brain Component -->\r\n");
      out.write("\r\n");
      out.write("      <h2>CONTACT<span>US</span></h2>\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"row justify-content-lg-center\">\r\n");
      out.write("      <div class=\"col-12 col-lg-9\" id=\"contact\">\r\n");
      out.write("        <div class=\" border rounded shadow-sm overflow-hidden\">\r\n");
      out.write("\r\n");
      out.write("          <form action=\"#!\">\r\n");
      out.write("            <div class=\"row gy-4 gy-xl-5 p-4 p-xl-5\">\r\n");
      out.write("              <div class=\"col-12\">\r\n");
      out.write("                <label for=\"fullname\" class=\"form-label\">Full Name <span class=\"text-danger\">*</span></label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"fullname\" name=\"fullname\" value=\"\" required>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-12 col-md-6\">\r\n");
      out.write("                <label for=\"email\" class=\"form-label\">Email <span class=\"text-danger\">*</span></label>\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                  <span class=\"input-group-text\">\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-envelope\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                      <path d=\"M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4Zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2Zm13 2.383-4.708 2.825L15 11.105V5.383Zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741ZM1 11.105l4.708-2.897L1 5.383v5.722Z\" />\r\n");
      out.write("                    </svg>\r\n");
      out.write("                  </span>\r\n");
      out.write("                  <input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" value=\"\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-12 col-md-6\">\r\n");
      out.write("                <label for=\"phone\" class=\"form-label\">Phone Number</label>\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                  <span class=\"input-group-text\">\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-telephone\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                      <path d=\"M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.568 17.568 0 0 0 4.168 6.608 17.569 17.569 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.678.678 0 0 0-.58-.122l-2.19.547a1.745 1.745 0 0 1-1.657-.459L5.482 8.062a1.745 1.745 0 0 1-.46-1.657l.548-2.19a.678.678 0 0 0-.122-.58L3.654 1.328zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z\" />\r\n");
      out.write("                    </svg>\r\n");
      out.write("                  </span>\r\n");
      out.write("                  <input type=\"tel\" class=\"form-control\" id=\"phone\" name=\"phone\" value=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-12\">\r\n");
      out.write("                <label for=\"message\" class=\"form-label\">Message <span class=\"text-danger\">*</span></label>\r\n");
      out.write("                <textarea class=\"form-control\" id=\"message\" name=\"message\" rows=\"3\" required></textarea>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-12\">\r\n");
      out.write("                <div class=\"d-grid\">\r\n");
      out.write("                  <div class=\"button\">\r\n");
      out.write("                    \r\n");
      out.write("                    <button data-mdb-ripple-init type=\"button\" class=\"btn btn-primary btn-block mb-4\">Submit </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </form>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write(" </section>\r\n");
      out.write("    </div>\r\n");
      out.write("  </dic>\r\n");
      out.write("   <div id=\"footer\">\r\n");
      out.write("    <div class=\"row footer\">\r\n");
      out.write("      <h2>foo<span>ter</span></h2>\r\n");
      out.write("      <div class=\"col-12\">\r\n");
      out.write("        <div class=\"container my-5\">\r\n");
      out.write("\r\n");
      out.write("          <!-- Footer -->\r\n");
      out.write("          <footer\r\n");
      out.write("                  class=\"text-center text-lg-start text-white\"\r\n");
      out.write("                  style=\"background-color: #1c2331\"\r\n");
      out.write("                  >\r\n");
      out.write("            <!-- Section: Social media -->\r\n");
      out.write("            <section\r\n");
      out.write("                     class=\"d-flex justify-content-between p-4\"\r\n");
      out.write("                     style=\"background-color: #ff004f\"\r\n");
      out.write("                     >\r\n");
      out.write("              <!-- Left -->\r\n");
      out.write("              <div class=\"me-5\">\r\n");
      out.write("                <span>Get connected with us on social networks:</span>\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- Left -->\r\n");
      out.write("        \r\n");
      out.write("              <!-- Right -->\r\n");
      out.write("              <div>\r\n");
      out.write("                <a href=\"\" class=\"text-white me-4\">\r\n");
      out.write("                  <i class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"\" class=\"text-white me-4\">\r\n");
      out.write("                  <i class=\"fab fa-twitter\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"\" class=\"text-white me-4\">\r\n");
      out.write("                  <i class=\"fab fa-google\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"\" class=\"text-white me-4\">\r\n");
      out.write("                  <i class=\"fab fa-instagram\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"\" class=\"text-white me-4\">\r\n");
      out.write("                  <i class=\"fab fa-linkedin\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"\" class=\"text-white me-4\">\r\n");
      out.write("                  <i class=\"fab fa-github\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- Right -->\r\n");
      out.write("            </section>\r\n");
      out.write("            <!-- Section: Social media -->\r\n");
      out.write("        \r\n");
      out.write("            <!-- Section: Links  -->\r\n");
      out.write("            <section class=\"\">\r\n");
      out.write("              <div class=\"container text-center text-md-start\">\r\n");
      out.write("                <!-- Grid row -->\r\n");
      out.write("                <div class=\"row mt-3\">\r\n");
      out.write("                  <!-- Grid column -->\r\n");
      out.write("                  <div class=\"col-md-3 col-lg-4 col-xl-3 mx-auto mb-4\">\r\n");
      out.write("                    <!-- Content -->\r\n");
      out.write("                    <h6 class=\"text-uppercase fw-bold\">Company name</h6>\r\n");
      out.write("                    <hr\r\n");
      out.write("                        class=\"mb-4 mt-0 d-inline-block mx-auto\"\r\n");
      out.write("                        style=\"width: 60px; background-color: #ff004f; height: 2px\"\r\n");
      out.write("                        />\r\n");
      out.write("                    <p>\r\n");
      out.write("                      Here you can use rows and columns to organize your footer\r\n");
      out.write("                      content. Lorem ipsum dolor sit amet, consectetur adipisicing\r\n");
      out.write("                      elit.\r\n");
      out.write("                    </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!-- Grid column -->\r\n");
      out.write("        \r\n");
      out.write("                  <!-- Grid column -->\r\n");
      out.write("                  <div class=\"col-md-2 col-lg-2 col-xl-2 mx-auto mb-4\">\r\n");
      out.write("                    <!-- Links -->\r\n");
      out.write("                    <h6 class=\"text-uppercase fw-bold\">Products</h6>\r\n");
      out.write("                    <hr\r\n");
      out.write("                        class=\"mb-4 mt-0 d-inline-block mx-auto\"\r\n");
      out.write("                        style=\"width: 60px; background-color: #ff004fff; height: 2px\"\r\n");
      out.write("                        />\r\n");
      out.write("                    <p>\r\n");
      out.write("                      <a href=\"#!\" class=\"text-white\">MDBootstrap</a>\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p>\r\n");
      out.write("                      <a href=\"#!\" class=\"text-white\">MDWordPress</a>\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p>\r\n");
      out.write("                      <a href=\"#!\" class=\"text-white\">BrandFlow</a>\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p>\r\n");
      out.write("                      <a href=\"#!\" class=\"text-white\">Bootstrap Angular</a>\r\n");
      out.write("                    </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!-- Grid column -->\r\n");
      out.write("        \r\n");
      out.write("                  <!-- Grid column -->\r\n");
      out.write("                  <div class=\"col-md-3 col-lg-2 col-xl-2 mx-auto mb-4\">\r\n");
      out.write("                    <!-- Links -->\r\n");
      out.write("                    <h6 class=\"text-uppercase fw-bold\">Useful links</h6>\r\n");
      out.write("                    <hr\r\n");
      out.write("                        class=\"mb-4 mt-0 d-inline-block mx-auto\"\r\n");
      out.write("                        style=\"width: 60px; background-color:#ff004f; height: 2px\"\r\n");
      out.write("                        />\r\n");
      out.write("                    <p>\r\n");
      out.write("                      <a href=\"#!\" class=\"text-white\">Your Account</a>\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p>\r\n");
      out.write("                      <a href=\"#!\" class=\"text-white\">Become an Affiliate</a>\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p>\r\n");
      out.write("                      <a href=\"#!\" class=\"text-white\">Shipping Rates</a>\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p>\r\n");
      out.write("                      <a href=\"#!\" class=\"text-white\">Help</a>\r\n");
      out.write("                    </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!-- Grid column -->\r\n");
      out.write("        \r\n");
      out.write("                  <!-- Grid column -->\r\n");
      out.write("                  <div class=\"col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4\">\r\n");
      out.write("                    <!-- Links -->\r\n");
      out.write("                    <h6 class=\"text-uppercase fw-bold\">Contact</h6>\r\n");
      out.write("                    <hr\r\n");
      out.write("                        class=\"mb-4 mt-0 d-inline-block mx-auto\"\r\n");
      out.write("                        style=\"width: 60px; background-color: #ff4da6; height: 2px\"\r\n");
      out.write("                        />\r\n");
      out.write("                    <p><i class=\"fas fa-home mr-3\"></i> New York, NY 10012, US</p>\r\n");
      out.write("                    <p><i class=\"fas fa-envelope mr-3\"></i> info@example.com</p>\r\n");
      out.write("                    <p><i class=\"fas fa-phone mr-3\"></i> + 01 234 567 88</p>\r\n");
      out.write("                    <p><i class=\"fas fa-print mr-3\"></i> + 01 234 567 89</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!-- Grid column -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Grid row -->\r\n");
      out.write("              </div>\r\n");
      out.write("            </section>\r\n");
      out.write("            <!-- Section: Links  -->\r\n");
      out.write("        \r\n");
      out.write("            <!-- Copyright -->\r\n");
      out.write("            <div\r\n");
      out.write("                 class=\"text-center p-3\"\r\n");
      out.write("                 style=\"background-color: rgba(0, 0, 0, 0.2)\"\r\n");
      out.write("                 >\r\n");
      out.write("              © 2020 Copyright:\r\n");
      out.write("              <a class=\"text-white\" href=\"https://mdbootstrap.com/\"\r\n");
      out.write("                 >MDBootstrap.com</a\r\n");
      out.write("                >\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Copyright -->\r\n");
      out.write("          </footer>\r\n");
      out.write("          <!-- Footer -->\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End of .container -->\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("   </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
