/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-05-09 08:45:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class CostumRegistration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/AdminPanel.jsp", Long.valueOf(1715236807705L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Costumr Registration Form</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CostumRegistration.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\" integrity=\"sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N\" crossorigin=\"anonymous\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"PanelCss.css\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!------ Include the above in your HEAD tag ---------->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"Panel.js\"></script>\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/014ca51276.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"experiment\">\r\n");
      out.write("		<div class=\"nav-side-menu\">\r\n");
      out.write("			<div class=\"brand\">Brand Logo</div>\r\n");
      out.write("			<i class=\"fa fa-bars fa-2x toggle-btn\" data-toggle=\"collapse\"\r\n");
      out.write("				data-target=\"#menu-content\"></i>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"menu-list\">\r\n");
      out.write("				<ul id=\"menu-content\" class=\"menu-content collapse out\">\r\n");
      out.write("					<li><a href=\"#\"> <i class=\"fa fa-dashboard fa-lg\"></i>\r\n");
      out.write("							Dashboard\r\n");
      out.write("					</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<li data-toggle=\"collapse\" data-target=\"#Admin\"\r\n");
      out.write("						class=\"collapsed\"><a href=\"#\"><i class=\"fa fa-user fa-lg\"></i>\r\n");
      out.write("							Admin <span class=\"arrow\"></span></a>\r\n");
      out.write("						<ul class=\"sub-menu collapse\" id=\"Admin\">\r\n");
      out.write("							<li><a href=\"AdminRegistration.jsp\">Add Admin</a></li>\r\n");
      out.write("							<li><a href=\"ViewAdmin.jsp\">View All Admin</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<li data-toggle=\"collapse\" data-target=\"#Employee\" class=\"collapsed\">\r\n");
      out.write("                <a href=\"#\"><i class=\"fa-solid fa-circle-user\"></i> Employee <span class=\"arrow\"></span></a>\r\n");
      out.write("                <ul class=\"sub-menu collapse\" id=\"Employee\">\r\n");
      out.write("                    <li><a href=\"EmplyeeAdd.jsp\">Add Employee</a></li>\r\n");
      out.write("                    <li><a href=\"ViewEmploye.jsp\">View All Employee</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("					<!-- Corrected Dropdown -->\r\n");
      out.write("					<li data-toggle=\"collapse\" data-target=\"#appointment\"\r\n");
      out.write("						class=\"collapsed\"><a href=\"#\"><i\r\n");
      out.write("							class=\"fa fa-calendar fa-lg\"></i> Appointment <span class=\"arrow\"></span></a>\r\n");
      out.write("						<ul class=\"sub-menu collapse\" id=\"appointment\">\r\n");
      out.write("							<li>Schedule Appointment</li>\r\n");
      out.write("							<li>View Appointments</li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<!-- End of Corrected Dropdown -->\r\n");
      out.write("\r\n");
      out.write("					<!-- Corrected Dropdown -->\r\n");
      out.write("					<li data-toggle=\"collapse\" data-target=\"#customer\"\r\n");
      out.write("						class=\"collapsed\"><a href=\"#\"><i class=\"fa-solid fa-car\"></i>Customer\r\n");
      out.write("							<span class=\"arrow\"></span></a>\r\n");
      out.write("						<ul class=\"sub-menu collapse\" id=\"customer\">\r\n");
      out.write("							<li>Add Customer</li>\r\n");
      out.write("							<li>View Customer</li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<li data-toggle=\"collapse\" data-target=\"#Inventory\"\r\n");
      out.write("						class=\"collapsed\"><a href=\"#\"><i\r\n");
      out.write("							class=\"fa-solid fa-warehouse\"></i>Inventory<span class=\"arrow\"></span></a>\r\n");
      out.write("						<ul class=\"sub-menu collapse\" id=\"Inventory\">\r\n");
      out.write("							<li>Schedule Appointment</li>\r\n");
      out.write("							<li>View Appointments</li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<!-- End of Corrected Dropdown -->\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"vh-100 maintask\">\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"mask d-flex align-items-center h-100\">\r\n");
      out.write("    <div class=\"container h-100\">\r\n");
      out.write("      <div class=\"row d-flex justify-content-center align-items-center h-100\">\r\n");
      out.write("        <div class=\"col-12 col-md-9 col-lg-7 col-xl-8\">\r\n");
      out.write("          <div class=\"card\" style=\"border-radius: 15px;\">\r\n");
      out.write("            <div class=\"card-body  p-5\" style=\"border-radius: 15px;\">\r\n");
      out.write("              <h2 class=\"text-uppercase text-center mb-5\">Costumer Registration</h2>\r\n");
      out.write("\r\n");
      out.write("              <form name=\"frm\" action=\"\" method=\"post\" >\r\n");
      out.write("\r\n");
      out.write("                <div data-mdb-input-init class=\"form-outline d-flex mb-4\">\r\n");
      out.write("                  <input type=\"text\" name=\"firstname\" id=\"form3Example1cg\" class=\"form-control form-control-lg\" value=\"\" placeholder=\"First Name\" />\r\n");
      out.write("               	  <input type=\"text\" name=\"lastname\" id=\"form3Example1cg\" class=\"form-control form-control-lg\" value=\"\" placeholder=\"Last Name\" />\r\n");
      out.write("                 <!--  <label class=\"form-label\" for=\"form3Example1cg\">Your Name</label> -->\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div data-mdb-input-init class=\"form-outline d-flex mb-4\">\r\n");
      out.write("                  <input type=\"email\" name=\"email\" id=\"form3Example1cg\" class=\"form-control form-control-lg\" value=\"\" placeholder=\"Email\" />\r\n");
      out.write("               	  <input type=\"contact\" name=\"contact\" id=\"form3Example1cg\" class=\"form-control form-control-lg\" value=\"\" placeholder=\"contact\" />\r\n");
      out.write("                 <!--  <label class=\"form-label\" for=\"form3Example1cg\">Your Name</label> -->\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div data-mdb-input-init class=\"form-outline mb-4\">\r\n");
      out.write("                  <input type=\"aderess\" name=\"username\" id=\"form3Example3cg\" class=\"form-control form-control-lg\" value=\"\" placeholder=\"Address\" />\r\n");
      out.write("                  <!-- <label class=\"form-label\" for=\"form3Example3cg\">Your Email</label> -->\r\n");
      out.write("                </div>\r\n");
      out.write("                  <hr>\r\n");
      out.write("                  <h3>vehicle details</h3>\r\n");
      out.write("                 <div data-mdb-input-init class=\"form-outline mb-4\">\r\n");
      out.write("                  <input type=\"Vehicle Number\" name=\"Vehicle Number\" id=\"form3Example3cg\" class=\"form-control form-control-lg\" value=\"\" placeholder=\"Vehicle Number\" />\r\n");
      out.write("                  <!-- <label class=\"form-label\" for=\"form3Example3cg\">Your Email</label> -->\r\n");
      out.write("                </div>\r\n");
      out.write("                 <div data-mdb-input-init class=\"form-outline mb-4\">\r\n");
      out.write("                  <input type=\"Vehicle Model\" name=\"Vehicle Model\" id=\"form3Example3cg\" class=\"form-control form-control-lg\" value=\"\" placeholder=\"Vehicle Model\" />\r\n");
      out.write("                  <!-- <label class=\"form-label\" for=\"form3Example3cg\">Your Email</label> -->\r\n");
      out.write("                </div>\r\n");
      out.write("                 <div data-mdb-input-init class=\"form-outline mb-4\">\r\n");
      out.write("                  <input type=\"Vehicle Year\" name=\"Vehicle Year\" id=\"form3Example3cg\" class=\"form-control form-control-lg\" value=\"\" placeholder=\"Vehicle Year\" />\r\n");
      out.write("                  <!-- <label class=\"form-label\" for=\"form3Example3cg\">Your Email</label> -->\r\n");
      out.write("                </div>\r\n");
      out.write("                 \r\n");
      out.write("                <div class=\"form-check d-flex justify-content-center mb-5\" >\r\n");
      out.write("                  <div class=\"d-flex justify-content-center\" style=\"width:60%;\">\r\n");
      out.write("                  <input class=\"form-check-input me-2\" type=\"checkbox\" value=\"\" id=\"form2Example3cg\" style=\"position:absolute; margin-right:300px;\" />\r\n");
      out.write("                  <label class=\"form-check-label\" for=\"form2Example3g\" style=\"\">\r\n");
      out.write("                    I agree all<a href=\"#!\" class=\"text-body\"><u>Terms & Conditions of Services</u></a>\r\n");
      out.write("                  </label>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                  <button type=\"submit\"\r\n");
      out.write("                    data-mdb-button-init data-mdb-ripple-init class=\"btn btn-secondary btn-block btn-lg text-body\" value=\"Submit\">Register</button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("              </form>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
