/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-05-10 12:06:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Model.*;

public final class EmployeeUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/AdminPanel.jsp", Long.valueOf(1715236807705L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("Model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"AdminUpdateCss.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\" integrity=\"sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N\" crossorigin=\"anonymous\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"PanelCss.css\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!------ Include the above in your HEAD tag ---------->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"Panel.js\"></script>\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/014ca51276.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"experiment\">\r\n");
      out.write("		<div class=\"nav-side-menu\">\r\n");
      out.write("			<div class=\"brand\">Brand Logo</div>\r\n");
      out.write("			<i class=\"fa fa-bars fa-2x toggle-btn\" data-toggle=\"collapse\"\r\n");
      out.write("				data-target=\"#menu-content\"></i>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"menu-list\">\r\n");
      out.write("				<ul id=\"menu-content\" class=\"menu-content collapse out\">\r\n");
      out.write("					<li><a href=\"#\"> <i class=\"fa fa-dashboard fa-lg\"></i>\r\n");
      out.write("							Dashboard\r\n");
      out.write("					</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<li data-toggle=\"collapse\" data-target=\"#Admin\"\r\n");
      out.write("						class=\"collapsed\"><a href=\"#\"><i class=\"fa fa-user fa-lg\"></i>\r\n");
      out.write("							Admin <span class=\"arrow\"></span></a>\r\n");
      out.write("						<ul class=\"sub-menu collapse\" id=\"Admin\">\r\n");
      out.write("							<li><a href=\"AdminRegistration.jsp\">Add Admin</a></li>\r\n");
      out.write("							<li><a href=\"ViewAdmin.jsp\">View All Admin</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<li data-toggle=\"collapse\" data-target=\"#Employee\" class=\"collapsed\">\r\n");
      out.write("                <a href=\"#\"><i class=\"fa-solid fa-circle-user\"></i> Employee <span class=\"arrow\"></span></a>\r\n");
      out.write("                <ul class=\"sub-menu collapse\" id=\"Employee\">\r\n");
      out.write("                    <li><a href=\"EmplyeeAdd.jsp\">Add Employee</a></li>\r\n");
      out.write("                    <li><a href=\"ViewEmploye.jsp\">View All Employee</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("					<!-- Corrected Dropdown -->\r\n");
      out.write("					<li data-toggle=\"collapse\" data-target=\"#appointment\"\r\n");
      out.write("						class=\"collapsed\"><a href=\"#\"><i\r\n");
      out.write("							class=\"fa fa-calendar fa-lg\"></i> Appointment <span class=\"arrow\"></span></a>\r\n");
      out.write("						<ul class=\"sub-menu collapse\" id=\"appointment\">\r\n");
      out.write("							<li>Schedule Appointment</li>\r\n");
      out.write("							<li>View Appointments</li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<!-- End of Corrected Dropdown -->\r\n");
      out.write("\r\n");
      out.write("					<!-- Corrected Dropdown -->\r\n");
      out.write("					<li data-toggle=\"collapse\" data-target=\"#customer\"\r\n");
      out.write("						class=\"collapsed\"><a href=\"#\"><i class=\"fa-solid fa-car\"></i>Customer\r\n");
      out.write("							<span class=\"arrow\"></span></a>\r\n");
      out.write("						<ul class=\"sub-menu collapse\" id=\"customer\">\r\n");
      out.write("							<li>Add Customer</li>\r\n");
      out.write("							<li>View Customer</li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<li data-toggle=\"collapse\" data-target=\"#Inventory\"\r\n");
      out.write("						class=\"collapsed\"><a href=\"#\"><i\r\n");
      out.write("							class=\"fa-solid fa-warehouse\"></i>Inventory<span class=\"arrow\"></span></a>\r\n");
      out.write("						<ul class=\"sub-menu collapse\" id=\"Inventory\">\r\n");
      out.write("							<li>Schedule Appointment</li>\r\n");
      out.write("							<li>View Appointments</li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<!-- End of Corrected Dropdown -->\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"vh-100 maintask\">\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"mask d-flex align-items-center h-100\">\r\n");
      out.write("    <div class=\"container h-100\">\r\n");
      out.write("      <div class=\"row d-flex justify-content-center align-items-center h-100\">\r\n");
      out.write("        <div class=\"col-12 col-md-9 col-lg-7 col-xl-8\">\r\n");
      out.write("          <div class=\"card\" style=\"border-radius: 15px;\">\r\n");
      out.write("            <div class=\"card-body  p-5\" style=\"border-radius: 15px;\">\r\n");
      out.write("              <h2 class=\"text-uppercase text-center mb-5\">Employee <span>Update</span></h2>\r\n");
      out.write("              \r\n");
      out.write("              ");

              int EId=Integer.parseInt(request.getParameter("EId"));
              String FirstName=request.getParameter("FirstName");
              String LastName=request.getParameter("LastName");
              String Email=request.getParameter("Email");
              String Contact=request.getParameter("Contact");
              String Address=request.getParameter("Address");
              String Username=request.getParameter("Username");
          
              
      out.write("\r\n");
      out.write("              ");

              String Status=(String)request.getAttribute("Status");
              if(Status!=null&&!Status.isEmpty()){
            	 
      out.write("\r\n");
      out.write("            	 <h2>");
      out.print(Status );
      out.write("</h2>\r\n");
      out.write("            	 ");

              }
              
      out.write("\r\n");
      out.write("             \r\n");
      out.write("              <h3>Employee Id : ");
      out.print(EId );
      out.write("</h3>\r\n");
      out.write("              <form name=\"frm\" action=\"EmployeeUpdate\" method=\"post\" >\r\n");
      out.write("\r\n");
      out.write("                <div data-mdb-input-init class=\"form-outline d-flex mb-4\">\r\n");
      out.write("                <input type=\"hidden\" name=\"EId\" value=\"");
      out.print(EId);
      out.write("\"/>\r\n");
      out.write("                  <input type=\"text\" name=\"FirstName\" id=\"form3Example1cg\" class=\"form-control form-control-lg\" value=\"");
      out.print(FirstName );
      out.write("\" placeholder=\"Enter First Name\" required />\r\n");
      out.write("               	  <input type=\"text\" name=\"LastName\" id=\"form3Example1cg\" class=\"form-control form-control-lg\" value=\"");
      out.print(LastName );
      out.write("\" placeholder=\"Enter Last Name\" required />\r\n");
      out.write("                 <!--  <label class=\"form-label\" for=\"form3Example1cg\">Your Name</label> -->\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div data-mdb-input-init class=\"form-outline d-flex mb-4\">\r\n");
      out.write("                  <input type=\"email\" name=\"Email\" id=\"form3Example1cg\" class=\"form-control form-control-lg\" value=\"");
      out.print(Email );
      out.write("\" placeholder=\"Enter Email\" required />\r\n");
      out.write("               	  <input type=\"text\" name=\"Contact\" id=\"form3Example1cg\" class=\"form-control form-control-lg\" value=\"");
      out.print(Contact );
      out.write("\" placeholder=\"Enter contact\" required />\r\n");
      out.write("                 <!--  <label class=\"form-label\" for=\"form3Example1cg\">Your Name</label> -->\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div data-mdb-input-init class=\"form-outline d-flex mb-4\">\r\n");
      out.write("                  <input type=\"text\" name=\"Username\" id=\"form3Example1cg\" class=\"form-control form-control-lg\" value=\"");
      out.print(Username );
      out.write("\" placeholder=\"Enter UserName\" required />\r\n");
      out.write("               	  <input type=\"password\" name=\"Oldpassword\" id=\"form3Example1cg\" class=\"form-control form-control-lg\" value=\"\" placeholder=\"Enter Old password\" required />\r\n");
      out.write("                 <!--  <label class=\"form-label\" for=\"form3Example1cg\">Your Name</label> -->\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div data-mdb-input-init class=\"form-outline d-flex mb-4\">\r\n");
      out.write("                  <input type=\"password\" name=\"Newpassword\" id=\"form3Example1cg\" class=\"form-control form-control-lg\" value=\"\" placeholder=\"Enter New password\" required />\r\n");
      out.write("               	  <input type=\"password\" name=\"Confirmpassword\" id=\"form3Example1cg\" class=\"form-control form-control-lg\" value=\"\" placeholder=\" confirm password\" required />\r\n");
      out.write("                 <!--  <label class=\"form-label\" for=\"form3Example1cg\">Your Name</label> -->\r\n");
      out.write("                </div>\r\n");
      out.write("                 \r\n");
      out.write("                  <div data-mdb-input-init class=\"form-outline d-flex mb-4\">\r\n");
      out.write("                  <input type=\"text\" name=\"Address\" id=\"form5Example1cga\" class=\"form-control \" value=\"");
      out.print(Address );
      out.write("\" placeholder=\"Enter Address\" required />\r\n");
      out.write("               	 \r\n");
      out.write("                </div>\r\n");
      out.write("                 \r\n");
      out.write("                  \r\n");
      out.write("                 \r\n");
      out.write("                <div class=\"form-check d-flex justify-content-center mb-5\" >\r\n");
      out.write("                  <div class=\"d-flex justify-content-center\" style=\"width:60%;\">\r\n");
      out.write("                  <input class=\"form-check-input me-2\" type=\"checkbox\" value=\"\" id=\"form2Example3cg\" style=\"position:absolute; margin-right:300px;\" />\r\n");
      out.write("                  <label class=\"form-check-label\" for=\"form2Example3g\" style=\"\">\r\n");
      out.write("                    I agree all<a href=\"#!\" class=\"text-body\"><u>Terms & Conditions of Services</u></a>\r\n");
      out.write("                  </label>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                  <button type=\"submit\"\r\n");
      out.write("                    data-mdb-button-init data-mdb-ripple-init class=\"btn btn-danger btn-block btn-lg text-body\" value=\"Submit\">Submit</button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("              </form>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
