/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-05-26 05:20:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class homepage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"Homepag.css\">\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/014ca51276.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-light bg-light fixed-top\" id=\"textcolor\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"#\" id=\"navbarC\">\r\n");
      out.write("                <img src=\"imge/car-logo.jpg\" alt=\"Car Logo\"> \r\n");
      out.write("                <span>JantaGarage</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("        \r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("                <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("                    <li class=\"nav-item active\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"#\">Home</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                     <li class=\"nav-item active\">\r\n");
      out.write("                      	<a class=\"nav-link\" href=\"Adminlogin.html\">Login</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"#about\">About</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"#Services\">Services</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"#Team\">Team</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"#Review\">Review</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"#Contact\">Contact</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("       \r\n");
      out.write("           <!-- carousel -->\r\n");
      out.write("\r\n");
      out.write("    <div id=\"carouselExampleIndicators\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("        <ol class=\"carousel-indicators\">\r\n");
      out.write("            <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("            <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"1\"></li>\r\n");
      out.write("            <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"2\"></li>\r\n");
      out.write("        </ol>\r\n");
      out.write("        <div class=\"carousel-inner\">\r\n");
      out.write("            <div class=\"carousel-item active\">\r\n");
      out.write("                <img class=\"d-block w-100 \" src=\"imge/bg-light.jpg\" alt=\"First slide\">\r\n");
      out.write("                <div class=\"carousel-caption  d-md-block  \">\r\n");
      out.write("                    \r\n");
      out.write("                    <h1>Welcome to</h1>\r\n");
      out.write("                    <h3>Janta<span>Garage</span></h3>\r\n");
      out.write("                    <p>At Janta Garage, we offer comprehensive car repair and maintenance services for all models. We will take care of your car...</p>\r\n");
      out.write("                    <div class=\"button\">\r\n");
      out.write("                        <a href=\"#\" class=\"btn btn-primary\">Book Now</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"carousel-item \">\r\n");
      out.write("                <img class=\"d-block w-100\" src=\"imge/blackcar@.jpg\" alt=\"Second slide\">\r\n");
      out.write("                <div class=\"carousel-caption  d-md-block\" >\r\n");
      out.write("                    <h1>Welcome to</h1>\r\n");
      out.write("                    <h3>Janta<span>Garage</span></h3>\r\n");
      out.write("                    <p>At Janta Garage, we offer comprehensive car repair and maintenance services for all models. We will take care of your car...</p>\r\n");
      out.write("                    <div class=\"button\">\r\n");
      out.write("                        <a href=\"#\" class=\"btn btn-primary\">Book Now</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"carousel-item\">\r\n");
      out.write("                <img class=\"d-block w-100\" src=\"imge/bg-light.jpg\" alt=\"Third slide\">\r\n");
      out.write("                <div class=\"carousel-caption  d-md-block\">\r\n");
      out.write("                    <h1>Welcome to</h1>\r\n");
      out.write("                    <h3>Janta<span>Garage</span></h3>\r\n");
      out.write("                    <p>At Janta Garage, we offer comprehensive car repair and maintenance services for all models. We will take care of your car...</p>\r\n");
      out.write("                    <div class=\"button\">\r\n");
      out.write("                        <a href=\"#\" class=\"btn btn-primary\">Book Now</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a class=\"carousel-control-prev\" href=\"#carouselExampleIndicators\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("            <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("            <span class=\"sr-only\">Previous</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"carousel-control-next\" href=\"#carouselExampleIndicators\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("            <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("            <span class=\"sr-only\">Next</span>\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("        <!-- About us -->\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <h1>About <span>Us</span></h1>\r\n");
      out.write("            <div class=\"row about\" id=\"about\">\r\n");
      out.write("                <div class=\"col-md-5 col-sm-12\" id=\"ab\">\r\n");
      out.write("                    <img src=\"imge/about@.jpg\" alt=\"About Image\" class=\"img-fluid\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-sm-12\" id=\"db\">\r\n");
      out.write("                    <h2>JantaGarage<span>Service</span></h2>\r\n");
      out.write("                    <p>When it comes to repairing or doing checkups on your cars, all our team combined has almost a century of practical experience. We aim to make our service as reasonably priced as possible. That's why we cut on all unessential business expenses.</p>\r\n");
      out.write("                    <h3>Why Choose Us</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>FREE Loaner Cars;</li>\r\n");
      out.write("                        <li>FREE Shuttle Service;</li>\r\n");
      out.write("                        <li>Te Dent repair</li>\r\n");
      out.write("                        <li>Paint scratch repair</li>\r\n");
      out.write("                        <li>Tire installation</li>\r\n");
      out.write("                        <li>Wheel alignment</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("    <!-- services coloum -->\r\n");
      out.write("    <section class=\"wrapper\" id=\"Services\">\r\n");
      out.write("        <div class=\"container-fostrap\">\r\n");
      out.write("            <div>\r\n");
      out.write("            \r\n");
      out.write("                <h1 class=\"heading\">Our <span>Services</span></h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"content\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-xs-12 col-sm-4\">\r\n");
      out.write("                            <div class=\"card\">\r\n");
      out.write("                                <a class=\"img-card\" href=\"http://www.fostrap.com/2016/03/bootstrap-3-carousel-fade-effect.html\">\r\n");
      out.write("                                <img src=\"imge/oil2.jpeg\" />\r\n");
      out.write("                              </a>\r\n");
      out.write("                                <div class=\"card-content\">\r\n");
      out.write("                                    <h4 class=\"card-title\">\r\n");
      out.write("                                        <a href=\"http://www.fostrap.com/2016/03/bootstrap-3-carousel-fade-effect.html\">Oil Changess\r\n");
      out.write("                                      </a>\r\n");
      out.write("                                    </h4>\r\n");
      out.write("                                    <p class=\"\">\r\n");
      out.write("                                        Tutorial to make a carousel bootstrap by adding more wonderful effect fadein ...\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-read-more\">\r\n");
      out.write("                                    <a href=\"http://www.fostrap.com/2016/03/bootstrap-3-carousel-fade-effect.html\" class=\"btn btn-link btn-block\">\r\n");
      out.write("                                        Read More\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xs-12 col-sm-4\">\r\n");
      out.write("                            <div class=\"card\">\r\n");
      out.write("                                <a class=\"img-card\" href=\"http://www.fostrap.com/2016/03/5-button-hover-animation-effects-css3.html\">\r\n");
      out.write("                                <img src=\"imge/tyre instalation.jpeg\" />\r\n");
      out.write("                              </a>\r\n");
      out.write("                                <div class=\"card-content\">\r\n");
      out.write("                                    <h4 class=\"card-title\">\r\n");
      out.write("                                        <a href=\"http://www.fostrap.com/2016/02/awesome-material-design-responsive-menu.html\">Tyre Instalation\r\n");
      out.write("                                      </a>\r\n");
      out.write("                                    </h4>\r\n");
      out.write("                                    <p class=\"\">\r\n");
      out.write("                                        Tutorial to make a carousel bootstrap by adding more wonderful effect fadein ...\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-read-more\">\r\n");
      out.write("                                    <a href=\"https://codepen.io/wisnust10/full/ZWERZK/\" class=\"btn btn-link btn-block\">\r\n");
      out.write("                                        Read More\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xs-12 col-sm-4\">\r\n");
      out.write("                            <div class=\"card\">\r\n");
      out.write("                                <a class=\"img-card\" href=\"http://www.fostrap.com/2016/03/5-button-hover-animation-effects-css3.html\">\r\n");
      out.write("                                <img src=\"imge/Air-conditioning.png\" />\r\n");
      out.write("                              </a>\r\n");
      out.write("                                <div class=\"card-content\">\r\n");
      out.write("                                    <h4 class=\"card-title\">\r\n");
      out.write("                                        <a href=\"http://www.fostrap.com/2016/03/5-button-hover-animation-effects-css3.html\">Air Conditioning\r\n");
      out.write("                                      </a>\r\n");
      out.write("                                    </h4>\r\n");
      out.write("                                    <p class=\"\">\r\n");
      out.write("                                        Tutorial to make a carousel bootstrap by adding more wonderful effect fadein ...\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-read-more\">\r\n");
      out.write("                                    <a href=\"http://www.fostrap.com/2016/03/5-button-hover-animation-effects-css3.html\" class=\"btn btn-link btn-block\">\r\n");
      out.write("                                        Read More\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("      <!-- Our Team -->\r\n");
      out.write("      <section class=\"wrapper\" id=\"Team\" >\r\n");
      out.write("        <div class=\"container-fostrap\">\r\n");
      out.write("            <div>\r\n");
      out.write("            \r\n");
      out.write("                <h1 class=\"heading\">Our <span>Team</span></h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"content\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-xs-12 col-sm-4\">\r\n");
      out.write("                            <div class=\"card\">\r\n");
      out.write("                                <a class=\"img-card\" href=\"http://www.fostrap.com/2016/03/bootstrap-3-carousel-fade-effect.html\">\r\n");
      out.write("                                <img src=\"imge/Sam1.jpg\" />\r\n");
      out.write("                              </a>\r\n");
      out.write("                                <div class=\"card-content\">\r\n");
      out.write("                                    <h4 class=\"card-title\">\r\n");
      out.write("                                        <a href=\"http://www.fostrap.com/2016/03/bootstrap-3-carousel-fade-effect.html\">Sam\r\n");
      out.write("                                      </a>\r\n");
      out.write("                                    </h4>\r\n");
      out.write("                                    <p class=\"\">\r\n");
      out.write("                                        Tutorial to make a carousel bootstrap by adding more wonderful effect fadein ...\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-read-more\">\r\n");
      out.write("                                    <a href=\"http://www.fostrap.com/2016/03/bootstrap-3-carousel-fade-effect.html\" class=\"btn btn-link btn-block\">\r\n");
      out.write("                                        Read More\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xs-12 col-sm-4\">\r\n");
      out.write("                            <div class=\"card\">\r\n");
      out.write("                                <a class=\"img-card\" href=\"http://www.fostrap.com/2016/03/5-button-hover-animation-effects-css3.html\">\r\n");
      out.write("                                <img src=\"imge/devid.avif\" />\r\n");
      out.write("                              </a>\r\n");
      out.write("                                <div class=\"card-content\">\r\n");
      out.write("                                    <h4 class=\"card-title\">\r\n");
      out.write("                                        <a href=\"http://www.fostrap.com/2016/02/awesome-material-design-responsive-menu.html\">Devid\r\n");
      out.write("                                      </a>\r\n");
      out.write("                                    </h4>\r\n");
      out.write("                                    <p class=\"\">\r\n");
      out.write("                                        Tutorial to make a carousel bootstrap by adding more wonderful effect fadein ...\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-read-more\">\r\n");
      out.write("                                    <a href=\"https://codepen.io/wisnust10/full/ZWERZK/\" class=\"btn btn-link btn-block\">\r\n");
      out.write("                                        Read More\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xs-12 col-sm-4\">\r\n");
      out.write("                            <div class=\"card\">\r\n");
      out.write("                                <a class=\"img-card\" href=\"http://www.fostrap.com/2016/03/5-button-hover-animation-effects-css3.html\">\r\n");
      out.write("                                <img src=\"imge/alisa1.jpg\" />\r\n");
      out.write("                              </a>\r\n");
      out.write("                                <div class=\"card-content\">\r\n");
      out.write("                                    <h4 class=\"card-title\">\r\n");
      out.write("                                        <a href=\"http://www.fostrap.com/2016/03/5-button-hover-animation-effects-css3.html\">Alisa</a>\r\n");
      out.write("                                      </a>\r\n");
      out.write("                                    </h4>\r\n");
      out.write("                                    <p class=\"\">\r\n");
      out.write("                                        Tutorial to make a carousel bootstrap by adding more wonderful effect fadein ...\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-read-more\">\r\n");
      out.write("                                    <a href=\"http://www.fostrap.com/2016/03/5-button-hover-animation-effects-css3.html\" class=\"btn btn-link btn-block\">\r\n");
      out.write("                                        Read More\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Cliert Revies -->\r\n");
      out.write("    <div class=\"row Review\" id=\"Review\">\r\n");
      out.write("        <div class=\"textR\">\r\n");
      out.write("            <h2>Our <span>Review</span></h2>\r\n");
      out.write("            <section>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-4 mb-4\">\r\n");
      out.write("                        <div class=\"card testimonial-card\">\r\n");
      out.write("                            <div class=\"card-up\" style=\"background-color:black\"></div>\r\n");
      out.write("                            <div class=\"avatar mx-auto bg-white\">\r\n");
      out.write("                                <img src=\"https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(1).webp\" class=\"rounded-circle img-fluid\" />\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <h4 class=\"mb-4\">Bela Smantha</h4>\r\n");
      out.write("                                <hr />\r\n");
      out.write("                                <p class=\"dark-grey-text mt-4\">\r\n");
      out.write("                                    <i class=\"fas fa-quote-left pe-2\"></i>Lorem ipsum dolor sit amet eos adipisci,\r\n");
      out.write("                                    consectetur adipisicing elit.\r\n");
      out.write("                                    <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                    <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                    <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                    <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4 mb-4\">\r\n");
      out.write("                        <div class=\"card testimonial-card\">\r\n");
      out.write("                            <div class=\"card-up\" style=\"background-color:black\"></div>\r\n");
      out.write("                            <div class=\"avatar mx-auto bg-white\">\r\n");
      out.write("                                <img src=\"https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(2).webp\" class=\"rounded-circle img-fluid\" />\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <h4 class=\"mb-4\">Lisa Cudrow</h4>\r\n");
      out.write("                                <hr />\r\n");
      out.write("                                <p class=\"dark-grey-text mt-4\">\r\n");
      out.write("                                    <i class=\"fas fa-quote-left pe-2\"></i>Neque cupiditate assumenda in maiores\r\n");
      out.write("                                    repudi mollitia architecto.\r\n");
      out.write("                                    <i class=\"fa-solid fa-star\"></i><i class=\"fa-solid fa-star\"></i><i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4 mb-4\">\r\n");
      out.write("                        <div class=\"card testimonial-card\">\r\n");
      out.write("                            <div class=\"card-up\"  style=\"background-color:black\"></div>\r\n");
      out.write("                            <div class=\"avatar mx-auto bg-white\">\r\n");
      out.write("                                <img src=\"https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(9).webp\" class=\"rounded-circle img-fluid\" />\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <h4 class=\"mb-4\">John Smith</h4>\r\n");
      out.write("                                <hr />\r\n");
      out.write("                                <p class=\"dark-grey-text mt-4\">\r\n");
      out.write("                                    <i class=\"fas fa-quote-left pe-2\"></i>Delectus impedit saepe officiis ab\r\n");
      out.write("                                    aliquam repellat rem unde.\r\n");
      out.write("                                    <i class=\"fa-solid fa-star\"></i><i class=\"fa-solid fa-star\"></i><i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("       <!-- Contact -->\r\n");
      out.write("         \r\n");
      out.write("       <div class=\"Contact\" id=\"Contact\">\r\n");
      out.write("        <h1>Contact<span>Us</span></h1>\r\n");
      out.write("       </div>\r\n");
      out.write("       \r\n");
      out.write("    \r\n");
      out.write("       <div class=\"container-contact\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-6 offset-md-3\">\r\n");
      out.write("                <div class=\"Section\">\r\n");
      out.write("                    <form action=\"\">\r\n");
      out.write("                        <div class=\"input-box\">\r\n");
      out.write("                            <input type=\"text\" placeholder=\"Name\" required><i class=\"fa-solid fa-user\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"input-box\">\r\n");
      out.write("                            <input type=\"number\" placeholder=\"9146248476\" required autofill=\"off\">\r\n");
      out.write("                            <i class=\"fa-duotone fa-phone\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"input-box\">\r\n");
      out.write("                            <input type=\"email\" placeholder=\"prtikrindhe025@gmail.com\" required autofill=\"off\">\r\n");
      out.write("                            <i class=\"fa-solid fa-envelope\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <button type=\"submit\" id=\"btn\">Submit</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("        \r\n");
      out.write("      <!-- footer -->\r\n");
      out.write("      <footer class= \"text-center mt-2\" id=\"footer\">\r\n");
      out.write("        <!-- Grid container -->\r\n");
      out.write("        <div class=\"container p-4 pb-0\">\r\n");
      out.write("          <!-- Section: Social media -->\r\n");
      out.write("          <section class=\"mb-4\">\r\n");
      out.write("            <!-- Facebook -->\r\n");
      out.write("            <a\r\n");
      out.write("            data-mdb-ripple-init\r\n");
      out.write("              class=\"btn text-white btn-floating m-1\"\r\n");
      out.write("              style=\"background-color: #3b5998;\"\r\n");
      out.write("              href=\"#!\"\r\n");
      out.write("              role=\"button\"\r\n");
      out.write("              ><i class=\"fab fa-facebook-f\"></i\r\n");
      out.write("            ></a>\r\n");
      out.write("      \r\n");
      out.write("            <!-- Twitter -->\r\n");
      out.write("            <a\r\n");
      out.write("              data-mdb-ripple-init\r\n");
      out.write("              class=\"btn text-white btn-floating m-1\"\r\n");
      out.write("              style=\"background-color: #55acee;\"\r\n");
      out.write("              href=\"#!\"\r\n");
      out.write("              role=\"button\"\r\n");
      out.write("              ><i class=\"fab fa-twitter\"></i\r\n");
      out.write("            ></a>\r\n");
      out.write("      \r\n");
      out.write("            <!-- Google -->\r\n");
      out.write("            <a\r\n");
      out.write("              data-mdb-ripple-init\r\n");
      out.write("              class=\"btn text-white btn-floating m-1\"\r\n");
      out.write("              style=\"background-color: #dd4b39;\"\r\n");
      out.write("              href=\"#!\"\r\n");
      out.write("              role=\"button\"\r\n");
      out.write("              ><i class=\"fab fa-google\"></i\r\n");
      out.write("            ></a>\r\n");
      out.write("      \r\n");
      out.write("            <!-- Instagram -->\r\n");
      out.write("            <a\r\n");
      out.write("              data-mdb-ripple-init\r\n");
      out.write("              class=\"btn text-white btn-floating m-1\"\r\n");
      out.write("              style=\"background-color: #ac2bac;\"\r\n");
      out.write("              href=\"#!\"\r\n");
      out.write("              role=\"button\"\r\n");
      out.write("              ><i class=\"fab fa-instagram\"></i\r\n");
      out.write("            ></a>\r\n");
      out.write("      \r\n");
      out.write("            <!-- Linkedin -->\r\n");
      out.write("            <a\r\n");
      out.write("              data-mdb-ripple-init\r\n");
      out.write("              class=\"btn text-white btn-floating m-1\"\r\n");
      out.write("              style=\"background-color: #0082ca;\"\r\n");
      out.write("              href=\"#!\"\r\n");
      out.write("              role=\"button\"\r\n");
      out.write("              ><i class=\"fab fa-linkedin-in\"></i\r\n");
      out.write("            ></a>\r\n");
      out.write("            <!-- Github -->\r\n");
      out.write("            <a\r\n");
      out.write("              data-mdb-ripple-init\r\n");
      out.write("              class=\"btn text-white btn-floating m-1\"\r\n");
      out.write("              style=\"background-color: #333333;\"\r\n");
      out.write("              href=\"#!\"\r\n");
      out.write("              role=\"button\"\r\n");
      out.write("              ><i class=\"fab fa-github\"></i\r\n");
      out.write("            ></a>\r\n");
      out.write("            <div class=\"text-center p-3\" style=\"background-color: rgba(0, 0, 0, 0.05);\">\r\n");
      out.write("                <p>@Copyright:<span>Pratik/Vaibhav</span>....<i class=\"fa-solid fa-heart\"></i></p>\r\n");
      out.write("                \r\n");
      out.write("                 \r\n");
      out.write("              </div>\r\n");
      out.write("          </section>\r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Grid container -->\r\n");
      out.write("       \r\n");
      out.write("        <!-- Copyright -->\r\n");
      out.write("        \r\n");
      out.write("        <!-- Copyright -->\r\n");
      out.write("      </footer>\r\n");
      out.write("\r\n");
      out.write("    <!-- jQuery first, then Popper.js, then Bootstrap JS -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
