/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-07-28 03:10:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Service.*;
import Model.*;
import java.util.*;

public final class ViewVehicles_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


VehicleService vehicleService =new VehicleServiceImpl();
CustomerService customerService =new CustomerServiceImpl();

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/AdminPanel.jsp", Long.valueOf(1722136089509L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("Model");
    _jspx_imports_packages.add("Service");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>View Vehicles Details</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"PanelCss.css\">\r\n");
      out.write(" <script src=\"https://kit.fontawesome.com/014ca51276.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Admin Panel</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"PanelCss.css\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!------ Include the above in your HEAD tag ---------->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"Panel.js\"></script>\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/014ca51276.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"experiment\">\r\n");
      out.write("		<div class=\"nav-side-menu\">\r\n");
      out.write("			<div class=\"brand\">Brand Logo</div>\r\n");
      out.write("			<i class=\"fa fa-bars fa-2x toggle-btn\" data-toggle=\"collapse\"\r\n");
      out.write("				data-target=\"#menu-content\"></i>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"menu-list\">\r\n");
      out.write("				<ul id=\"menu-content\" class=\"menu-content collapse out\">\r\n");
      out.write("					<li><a href=\"#\"> <i class=\"fa fa-dashboard fa-lg\"></i>\r\n");
      out.write("							Dashboard\r\n");
      out.write("					</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<li data-toggle=\"collapse\" data-target=\"#Admin\"\r\n");
      out.write("						class=\"collapsed\"><a href=\"#\"><i class=\"fa fa-user fa-lg\"></i>\r\n");
      out.write("							Admin <span class=\"arrow\"></span></a>\r\n");
      out.write("						<ul class=\"sub-menu collapse\" id=\"Admin\">\r\n");
      out.write("							<li><a href=\"AdminRegistration.jsp\">Add Admin</a></li>\r\n");
      out.write("							<li><a href=\"ViewAdmin.jsp\">View All Admin</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<li data-toggle=\"collapse\" data-target=\"#Employee\" class=\"collapsed\">\r\n");
      out.write("                <a href=\"#\"><i class=\"fa-solid fa-circle-user\"></i> Employee <span class=\"arrow\"></span></a>\r\n");
      out.write("                <ul class=\"sub-menu collapse\" id=\"Employee\">\r\n");
      out.write("                    <li><a href=\"EmplyeeAdd.jsp\">Add Employee</a></li>\r\n");
      out.write("                    <li><a href=\"ViewEmploye.jsp\">View All Employee</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("					<!-- Corrected Dropdown -->\r\n");
      out.write("					<li data-toggle=\"collapse\" data-target=\"#appointment\"\r\n");
      out.write("						class=\"collapsed\"><a href=\"#\"><i\r\n");
      out.write("							class=\"fa fa-calendar fa-lg\"></i> Appointment <span class=\"arrow\"></span></a>\r\n");
      out.write("						<ul class=\"sub-menu collapse\" id=\"appointment\">\r\n");
      out.write("							<li><a href=\"BookAppointment.jsp\">Book Appointment</a></li>\r\n");
      out.write("							<li><a href=\"ViewAppointment.jsp\">View Appointments</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<!-- End of Corrected Dropdown -->\r\n");
      out.write("\r\n");
      out.write("					<!-- Corrected Dropdown -->\r\n");
      out.write("					<li data-toggle=\"collapse\" data-target=\"#customer\"\r\n");
      out.write("						class=\"collapsed\"><a href=\"#\"><i class=\"fa-solid fa-car\"></i>Customer\r\n");
      out.write("							<span class=\"arrow\"></span></a>\r\n");
      out.write("						<ul class=\"sub-menu collapse\" id=\"customer\">\r\n");
      out.write("						<!-- 	<li>Add Customer</li> -->\r\n");
      out.write("							<li><a href=\"ViewCustomer.jsp\">View Customer Details</a></li>\r\n");
      out.write("							<li><a href=\"ViewVehicles.jsp\">View Vehicle Details</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<li data-toggle=\"collapse\" data-target=\"#Inventory\"\r\n");
      out.write("						class=\"collapsed\"><a href=\"#\"><i\r\n");
      out.write("							class=\"fa-solid fa-warehouse\"></i>Inventory<span class=\"arrow\"></span></a>\r\n");
      out.write("						<ul class=\"sub-menu collapse\" id=\"Inventory\">\r\n");
      out.write("							<li>Add Spear Parts</li>\r\n");
      out.write("							<li><a href=\"ViewSpearParts.jsp\">View Spear Parts</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<!-- End of Corrected Dropdown -->\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"maintaskpage\">\r\n");
      out.write("<table class=\"table\">\r\n");
      out.write("  <thead>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"col\">Sr.no</th>\r\n");
      out.write("      <th scope=\"col\">Vehicle Number</th>\r\n");
      out.write("      <th scope=\"col\">Model Name</th>\r\n");
      out.write("      <th scope=\"col\">Model Year</th>\r\n");
      out.write("      <th scope=\"col\">Vehicle Owner</th>\r\n");
      out.write("      <th scope=\"col\">Delete</th>\r\n");
      out.write("      <th scope=\"col\">Update</th>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </thead>\r\n");
      out.write("  <tbody>\r\n");
      out.write("    ");

    List<VehicleModel> list=vehicleService.getAllVehicle();
    int count=0;
    for(VehicleModel vehicleModel:list)
    {
    	
    
      out.write("\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\">");
      out.print(++count);
      out.write("</th>\r\n");
      out.write("      <td>");
      out.print( vehicleModel.getVehicle_Number());
      out.write("</td>\r\n");
      out.write("      <td>");
      out.print( vehicleModel.getModel());
      out.write("</td>\r\n");
      out.write("      <td>");
      out.print(vehicleModel.getYear() );
      out.write("</td>\r\n");
      out.write("      <td>");
      out.print( customerService.getCustomerNameByCId(vehicleModel.getCId()) );
      out.write("</td>\r\n");
      out.write("      <td><a href='VehicleDelete?VId=");
      out.print(vehicleModel.getVId());
      out.write("'><i class=\"fa-solid fa-trash\"></a></i></td>\r\n");
      out.write("      <td><a href='VehicleUpdate.jsp?vehicleId=");
      out.print(vehicleModel.getVId());
      out.write("'><i class=\"fa-solid fa-pen\"></i></a></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    ");
 
    }
    list.clear(); 
    	
    	  
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("  </tbody>\r\n");
      out.write("</table>\r\n");
      out.write("</section>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
